import ClientLayout from "@/components/layout/ClientLayout";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProfileCard from "@/components/layout/ProfileCard";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Card } from "@/components/ui/card";
import { Navbar } from "@/components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <div className="flex flex-col md:flex-row gap-4 p-6 md:max-w-[1400px] mx-auto">
            <ProfileCard />
            <Card className="md:w-[1100px] md:mx-auto">
              <Navbar />
              <main className="">
                <ClientLayout>{children}</ClientLayout>
              </main>
            </Card>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
